### PR TITLE
update/fix documentation generation for client and server

### PR DESCRIPTION
**Pull request by hthetiot**
Tasks:

- [x]  generate client doc
- [x]  generate server doc
- [x] remove generated doc from repository
- [ ] pubic doc on github.io 

Preview:
Screen Shot 2020-04-04 at 5 45 16 PM
Screen Shot 2020-04-04 at 5 45 40 PM

### CODE REVIEW

**Comment by TriStarGod** [comment]
When will this be merged? Its difficult to figure without current documentation.

**Comment by hthetiot** [comment]
@TriStarGod May be if you actulally runned the sample server and read the documentation here instead of complaining that would allow us to not having to waste time replying to you.
- https://github.com/open-easyrtc/open-easyrtc/tree/master/server_example#viewing-the-examples
- https://github.com/open-easyrtc/open-easyrtc/tree/master/docs
- https://github.com/open-easyrtc/open-easyrtc/tree/master/demos

**Comment by TriStarGod** [comment]
@hthetiot I did and I used all the above docs / samples. I was able to get it work well with Chrome but it failed on Firefox unless I modified it. I thought since the stuff I found was either 2 or 4 years old, they weren't up to date. Sorry to waste your time.

**Comment by hthetiot** [comment]
Thank you @TriStarGod I'm a bastard and I know it :)
>  I was able to get it work well with Chrome but it failed on Firefox unless I modified it.
Feel free to help us fixing the issue with Firefox :)
This one fix MediaStream end on Firefox already https://github.com/open-easyrtc/open-easyrtc/pull/37

PR are welcome :)
Sorry if I'm a jerk that to push you to look by yourself :p

**Comment by hthetiot** [comment]
Hey remember you need a TURN server ;)

**Pull request merged**
