### PR TITLE
Tlr changes

### PR DESCRIPTION
**Pull request by zcurchin**

### CODE REVIEW

**Comment by hthetiot** [comment]
no proper explanation for changes getPeerConnectionByUserId and mixed changes in PR.

**Comment by hthetiot** [comment]
Make new PR with proper description and dont mix other PR in it pls.

**Comment by zcurchin** [comment]
Sorry, wasn't intentional.

**Comment by hthetiot** [comment]
> Sorry, wasn't intentional.

@zcurchin  No problem, feel free to do another PR with only the change you need and why you think this changes are needed.

Thank you for trying :)

**Pull request closed without merging**
